workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      vars:
        XCODE_SCHEME: "Runner"
        XCODE_WORKSPACE: "Runner.xcworkspace"

    scripts:
      - name: Full Clean & Install
        script: |
          flutter clean
          flutter pub get
          cd ios
          # حذف المجلدات التي تخزن الإعدادات القديمة والمتعارضة
          rm -rf Pods Podfile.lock .symlinks DerivedData
          # تحديث مستودع CocoaPods لضمان جلب نسخ MLKit المتوافقة مع M2
          pod install --repo-update
          cd ..
      
      - name: Build iOS Simulator
        script: |
         flutter build ios \
         --simulator \
         --debug \
         --no-codesign \
         --no-tree-shake-icons

    artifacts:
      # المسار الصحيح لملف التطبيق الخاص بالمحاكي
      - build/ios/iphonesimulator/*.app