workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      groups:
        - firebase_credentials # إذا كنت تستخدم مجموعات متغيرات بيئة
      vars:
        XCODE_SCHEME: "Runner"
        XCODE_WORKSPACE: "Runner.xcworkspace"

    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
          # تحديث ملفات القفل لضمان التوافق مع Simulator
          flutter pub upgrade

      - name: Install CocoaPods and update Firebase
        script: |
          cd ios
          # تنظيف أي ملفات سابقة قد تسبب تعارضاً
          rm -rf Pods Podfile.lock
          # تثبيت الـ Pods مع تحديث المستودعات لضمان وجود FirebaseCore
          pod install --repo-update
          cd ..

      - name: Build iOS Simulator App
        script: |
          xcodebuild build \
            -workspace ios/$XCODE_WORKSPACE \
            -scheme $XCODE_SCHEME \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
            -derivedDataPath Build \
            ARCHS=x86_64 \
            VALID_ARCHS=x86_64 \
            CODE_SIGNING_ALLOWED=NO


    artifacts:
      - Build/Products/Debug-iphonesimulator/*.app
      - build/ios/iphoneos/*.app
