workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Flutter Clean
        script: flutter clean

      - name: Get Packages
        script: flutter pub get

      - name: Precache iOS
        script: flutter precache --ios

      - name: Install Pods
        script: |
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Build Simulator
        script: |
          flutter build ios \
            --simulator \
            --debug \
            --no-codesign

      - name: Zip App
        script: |
          cd build/ios/iphonesimulator
          zip -r Runner.zip Runner.app

    artifacts:
      - build/ios/iphonesimulator/*.zip