// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTWHI6o0HyBWACZU-8pazu5huwXo1X7hE',
    appId: '1:840926699694:web:1e1d88be3d81cc8a314d3f',
    messagingSenderId: '840926699694',
    projectId: 'maintenance-b7282',
    authDomain: 'maintenance-b7282.firebaseapp.com',
    storageBucket: 'maintenance-b7282.firebasestorage.app',
    measurementId: 'G-0SDV31CF01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-l6i06vfoBsz9C6BuLDMoqGY6h7AXmIQ',
    appId: '1:840926699694:android:d94b4af2bcaf2145314d3f',
    messagingSenderId: '840926699694',
    projectId: 'maintenance-b7282',
    storageBucket: 'maintenance-b7282.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATYqxN96rNhE-isJ0tV3c_KhStalmL4p0',
    appId: '1:840926699694:ios:8f786c10d74c7084314d3f',
    messagingSenderId: '840926699694',
    projectId: 'maintenance-b7282',
    storageBucket: 'maintenance-b7282.firebasestorage.app',
    androidClientId: '840926699694-557gts8ogtg9dvog7a90hpjme6p3dltk.apps.googleusercontent.com',
    iosClientId: '840926699694-1kv9un1rognlmkdpmekgkird0c9rg827.apps.googleusercontent.com',
    iosBundleId: 'com.example.maintenance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATYqxN96rNhE-isJ0tV3c_KhStalmL4p0',
    appId: '1:840926699694:ios:8f786c10d74c7084314d3f',
    messagingSenderId: '840926699694',
    projectId: 'maintenance-b7282',
    storageBucket: 'maintenance-b7282.firebasestorage.app',
    androidClientId: '840926699694-557gts8ogtg9dvog7a90hpjme6p3dltk.apps.googleusercontent.com',
    iosClientId: '840926699694-1kv9un1rognlmkdpmekgkird0c9rg827.apps.googleusercontent.com',
    iosBundleId: 'com.example.maintenance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhEjcgx2JlqB5Wt5jAW07BlSD3SVx3Ad4',
    appId: '1:840926699694:web:550df844ceb97969314d3f',
    messagingSenderId: '840926699694',
    projectId: 'maintenance-b7282',
    authDomain: 'maintenance-b7282.firebaseapp.com',
    storageBucket: 'maintenance-b7282.firebasestorage.app',
    measurementId: 'G-D0WP4RNEVN',
  );
}
