platform :ios, '15.5'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      # 1. إزالة أي قيم مسبقة لـ EXCLUDED_ARCHS لتجنب خطأ الـ Merge
      config.build_settings.delete 'EXCLUDED_ARCHS[sdk=iphonesimulator*]'
      
      # 2. توحيد نسخة النظام لضمان توافق MLKit
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5' [cite: 1, 4]
      
      # 3. حل مشكلة المعمارية للمحاكي بشكل صريح
      if config.build_settings['SDKROOT'] =~ /iphonesimulator/
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end

      # 4. تفعيل البناء للمعمارية النشطة فقط
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES' [cite: 4]
    end
  end
end
